---
path: stubs

oracle_home: /opt/oracle/instantclient_18_3

nls_lang: null

abbreviation_files:
  - default_abbreviations.txt

databases:
  - name: db_name
    pool:
      user: user
      password: pass
      threaded: true
      homogeneous: true
      min: 8
      max: 8
      encoding: UTF-8
      dsn:
        host: 127.0.0.1
        port: 1521
        sid: null
        service_name: some
    schemes:
      - name: billing
        no_package_name: billing_no_pkg
        exclude_packages:
          - nasty_bills
        exclude_routines:
          - espesially_nasty_routine
          - horrible_pkg.oh_no
        introspection_appendix:
          # "object_id" is unique for package routines
          # "subprogram_id" is unique for non-package routines
          # So, you should provide both of them, so the routine can be uniquely
          # identified
          # If you also provide "position", the additional info will be
          # applied for concrete argument
          - comment: billing.some_pkg.get_bills, _dbsg_result arguemnt
            object_id: 777
            subprogram_id: 44
            position: 0
            custom_type_schema: "BILLING"
            custom_type: "BILLS%ROWTYPE"

      - name: tickets
        exclude_routines: null
        include_routines:
          - only_this_one
          - and_that_one

      - name: "goodies"  # include everything for the scheme

# ******************************Logging Reference******************************
# Levels:
#   CRITICAL
#   ERROR
#   WARNING
#   INFO
#   DEBUG
#   NOTSET

# Format (record) Attributes:
#   %(asctime)s
#   %(filename)s
#   %(funcName)s
#   %(levelname)s
#   %(levelno)s
#   %(lineno)d
#   %(message)s
#   %(module)s
#   %(name)s
#   %(pathname)s
#   %(process)d
#   %(processName)s
#   %(thread)d
#   %(threadName)s

# Sources:
#   https://docs.python.org/3/library/logging
#   https://docs.python.org/3/library/logging.config
#   https://docs.python.org/3/library/logging.handlers
# ******************************Logging Reference******************************
logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    main:
      # "DBSG", or any other word before [PID] will become $programname in syslog
      format: >-
        DBSG[%(process)s]
        [%(levelname)s]
        [thread_id=%(thread)d]
        [version=%(app_version)s]
        [%(name)s]
        -> %(message)s
      datefmt: "%Y-%m-%d %H:%M:%S"
      class: logging.Formatter
  filters:
    app_version:
      "()": "dbsg.lib.configuration.APPVersionLoggingFilter"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: main
      stream: ext://sys.stdout
      filters:
        - app_version
    syslog:
      class: logging.handlers.SysLogHandler
      facility: local7
      address: /dev/log
      formatter: main
      filters:
        - app_version
  # The Root Logger
  root:
    handlers:
      - console
      - syslog
    level: DEBUG
  # "propagate: true" means "use the Root Logger's handlers"
  # Any unspecified loggers will inherit the Root Logger's setup
  loggers:
    marshmallow:
      level: WARNING
      propagate: true
    pyyaml:
      level: WARNING
      propagate: true
    cx_Oracle:
      level: DEBUG
      propagate: true
...
